// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/11/2025, 6:07:59 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/davidlarsen/Desktop/Projects/davidlarsen.me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/plugins/**/*.{js,ts,mjs}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/composables/**/*.{js,ts,mjs}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/utils/**/*.{js,ts,mjs}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/Projects/davidlarsen.me/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;