// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/10/2025, 9:57:34 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/plugins/**/*.{js,ts,mjs}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/composables/**/*.{js,ts,mjs}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/utils/**/*.{js,ts,mjs}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Downloads/tylernhoward.github.io-develop/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;