// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/17/2026, 7:20:18 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/plugins/**/*.{js,ts,mjs}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/composables/**/*.{js,ts,mjs}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/utils/**/*.{js,ts,mjs}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/davidlarsen/Desktop/projects/davidlarsen.me-main/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;